/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.portugol.analysis;

import org.sablecc.portugol.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseTInicioPrograma(TInicioPrograma node);
    void caseTFimPrograma(TFimPrograma node);
    void caseTPrograma(TPrograma node);
    void caseTConstante(TConstante node);
    void caseTLeiaConsole(TLeiaConsole node);
    void caseTEscrevaConsole(TEscrevaConsole node);
    void caseTSe(TSe node);
    void caseTEntao(TEntao node);
    void caseTSenao(TSenao node);
    void caseTFimSe(TFimSe node);
    void caseTAvalie(TAvalie node);
    void caseTCaso(TCaso node);
    void caseTFimAvalie(TFimAvalie node);
    void caseTEnquanto(TEnquanto node);
    void caseTFaca(TFaca node);
    void caseTFimEnquanto(TFimEnquanto node);
    void caseTRepita(TRepita node);
    void caseTAte(TAte node);
    void caseTPara(TPara node);
    void caseTDe(TDe node);
    void caseTFimPara(TFimPara node);
    void caseTPasso(TPasso node);
    void caseTMais(TMais node);
    void caseTMenos(TMenos node);
    void caseTMulti(TMulti node);
    void caseTDiv(TDiv node);
    void caseTLogIgual(TLogIgual node);
    void caseTLogDiferente(TLogDiferente node);
    void caseTLogMenorIgual(TLogMenorIgual node);
    void caseTLogMaiorIgual(TLogMaiorIgual node);
    void caseTLogMenor(TLogMenor node);
    void caseTLogMaior(TLogMaior node);
    void caseTNegacao(TNegacao node);
    void caseTLogE(TLogE node);
    void caseTLogOu(TLogOu node);
    void caseTLogOuExclusivo(TLogOuExclusivo node);
    void caseTTipoReal(TTipoReal node);
    void caseTTipoInt(TTipoInt node);
    void caseTTipoChar(TTipoChar node);
    void caseTId(TId node);
    void caseTNumero(TNumero node);
    void caseTCaractere(TCaractere node);
    void caseTComentLinha(TComentLinha node);
    void caseTVirgula(TVirgula node);
    void caseTDoisPontos(TDoisPontos node);
    void caseTPontoVirgula(TPontoVirgula node);
    void caseTAspasS(TAspasS node);
    void caseTAspasD(TAspasD node);
    void caseTAbreColchete(TAbreColchete node);
    void caseTFechaColchete(TFechaColchete node);
    void caseTAtribuicao(TAtribuicao node);
    void caseTAbreParentese(TAbreParentese node);
    void caseTFechaParentese(TFechaParentese node);
    void caseTBranco(TBranco node);
    void caseEOF(EOF node);
    void caseInvalidToken(InvalidToken node);
}
