/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.portugol.parser;

import org.sablecc.portugol.node.*;
import org.sablecc.portugol.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTInicioPrograma(@SuppressWarnings("unused") TInicioPrograma node)
    {
        this.index = 0;
    }

    @Override
    public void caseTFimPrograma(@SuppressWarnings("unused") TFimPrograma node)
    {
        this.index = 1;
    }

    @Override
    public void caseTComecaPrograma(@SuppressWarnings("unused") TComecaPrograma node)
    {
        this.index = 2;
    }

    @Override
    public void caseTConstante(@SuppressWarnings("unused") TConstante node)
    {
        this.index = 3;
    }

    @Override
    public void caseTLeiaConsole(@SuppressWarnings("unused") TLeiaConsole node)
    {
        this.index = 4;
    }

    @Override
    public void caseTEscrevaConsole(@SuppressWarnings("unused") TEscrevaConsole node)
    {
        this.index = 5;
    }

    @Override
    public void caseTSe(@SuppressWarnings("unused") TSe node)
    {
        this.index = 6;
    }

    @Override
    public void caseTEntao(@SuppressWarnings("unused") TEntao node)
    {
        this.index = 7;
    }

    @Override
    public void caseTSenao(@SuppressWarnings("unused") TSenao node)
    {
        this.index = 8;
    }

    @Override
    public void caseTFimSe(@SuppressWarnings("unused") TFimSe node)
    {
        this.index = 9;
    }

    @Override
    public void caseTAvalie(@SuppressWarnings("unused") TAvalie node)
    {
        this.index = 10;
    }

    @Override
    public void caseTCaso(@SuppressWarnings("unused") TCaso node)
    {
        this.index = 11;
    }

    @Override
    public void caseTFimAvalie(@SuppressWarnings("unused") TFimAvalie node)
    {
        this.index = 12;
    }

    @Override
    public void caseTEnquanto(@SuppressWarnings("unused") TEnquanto node)
    {
        this.index = 13;
    }

    @Override
    public void caseTFaca(@SuppressWarnings("unused") TFaca node)
    {
        this.index = 14;
    }

    @Override
    public void caseTFimEnquanto(@SuppressWarnings("unused") TFimEnquanto node)
    {
        this.index = 15;
    }

    @Override
    public void caseTRepita(@SuppressWarnings("unused") TRepita node)
    {
        this.index = 16;
    }

    @Override
    public void caseTAte(@SuppressWarnings("unused") TAte node)
    {
        this.index = 17;
    }

    @Override
    public void caseTPara(@SuppressWarnings("unused") TPara node)
    {
        this.index = 18;
    }

    @Override
    public void caseTDe(@SuppressWarnings("unused") TDe node)
    {
        this.index = 19;
    }

    @Override
    public void caseTFimPara(@SuppressWarnings("unused") TFimPara node)
    {
        this.index = 20;
    }

    @Override
    public void caseTPasso(@SuppressWarnings("unused") TPasso node)
    {
        this.index = 21;
    }

    @Override
    public void caseTTipoReal(@SuppressWarnings("unused") TTipoReal node)
    {
        this.index = 22;
    }

    @Override
    public void caseTTipoInt(@SuppressWarnings("unused") TTipoInt node)
    {
        this.index = 23;
    }

    @Override
    public void caseTTipoChar(@SuppressWarnings("unused") TTipoChar node)
    {
        this.index = 24;
    }

    @Override
    public void caseTSoma(@SuppressWarnings("unused") TSoma node)
    {
        this.index = 25;
    }

    @Override
    public void caseTSubtracao(@SuppressWarnings("unused") TSubtracao node)
    {
        this.index = 26;
    }

    @Override
    public void caseTMulti(@SuppressWarnings("unused") TMulti node)
    {
        this.index = 27;
    }

    @Override
    public void caseTDiv(@SuppressWarnings("unused") TDiv node)
    {
        this.index = 28;
    }

    @Override
    public void caseTIgualdade(@SuppressWarnings("unused") TIgualdade node)
    {
        this.index = 29;
    }

    @Override
    public void caseTDiferenca(@SuppressWarnings("unused") TDiferenca node)
    {
        this.index = 30;
    }

    @Override
    public void caseTMenorIgual(@SuppressWarnings("unused") TMenorIgual node)
    {
        this.index = 31;
    }

    @Override
    public void caseTMaiorIgual(@SuppressWarnings("unused") TMaiorIgual node)
    {
        this.index = 32;
    }

    @Override
    public void caseTMenor(@SuppressWarnings("unused") TMenor node)
    {
        this.index = 33;
    }

    @Override
    public void caseTMaior(@SuppressWarnings("unused") TMaior node)
    {
        this.index = 34;
    }

    @Override
    public void caseTNegacao(@SuppressWarnings("unused") TNegacao node)
    {
        this.index = 35;
    }

    @Override
    public void caseTConjuncao(@SuppressWarnings("unused") TConjuncao node)
    {
        this.index = 36;
    }

    @Override
    public void caseTDisjuncao(@SuppressWarnings("unused") TDisjuncao node)
    {
        this.index = 37;
    }

    @Override
    public void caseTDisjuncaoExc(@SuppressWarnings("unused") TDisjuncaoExc node)
    {
        this.index = 38;
    }

    @Override
    public void caseTAtribuicao(@SuppressWarnings("unused") TAtribuicao node)
    {
        this.index = 39;
    }

    @Override
    public void caseTId(@SuppressWarnings("unused") TId node)
    {
        this.index = 40;
    }

    @Override
    public void caseTNumeroInt(@SuppressWarnings("unused") TNumeroInt node)
    {
        this.index = 41;
    }

    @Override
    public void caseTNumeroReal(@SuppressWarnings("unused") TNumeroReal node)
    {
        this.index = 42;
    }

    @Override
    public void caseTString(@SuppressWarnings("unused") TString node)
    {
        this.index = 43;
    }

    @Override
    public void caseTVirgula(@SuppressWarnings("unused") TVirgula node)
    {
        this.index = 44;
    }

    @Override
    public void caseTDoisPontos(@SuppressWarnings("unused") TDoisPontos node)
    {
        this.index = 45;
    }

    @Override
    public void caseTPontoVirgula(@SuppressWarnings("unused") TPontoVirgula node)
    {
        this.index = 46;
    }

    @Override
    public void caseTAspasS(@SuppressWarnings("unused") TAspasS node)
    {
        this.index = 47;
    }

    @Override
    public void caseTAspasD(@SuppressWarnings("unused") TAspasD node)
    {
        this.index = 48;
    }

    @Override
    public void caseTAbreColchete(@SuppressWarnings("unused") TAbreColchete node)
    {
        this.index = 49;
    }

    @Override
    public void caseTFechaColchete(@SuppressWarnings("unused") TFechaColchete node)
    {
        this.index = 50;
    }

    @Override
    public void caseTAbreParentese(@SuppressWarnings("unused") TAbreParentese node)
    {
        this.index = 51;
    }

    @Override
    public void caseTFechaParentese(@SuppressWarnings("unused") TFechaParentese node)
    {
        this.index = 52;
    }

    @Override
    public void caseTComentarioFinal(@SuppressWarnings("unused") TComentarioFinal node)
    {
        this.index = 53;
    }

    @Override
    public void caseTComentarioMeio(@SuppressWarnings("unused") TComentarioMeio node)
    {
        this.index = 54;
    }

    @Override
    public void caseTBarra(@SuppressWarnings("unused") TBarra node)
    {
        this.index = 55;
    }

    @Override
    public void caseTAsterisco(@SuppressWarnings("unused") TAsterisco node)
    {
        this.index = 56;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 57;
    }
}
