/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.portugol.node;

import java.util.*;
import org.sablecc.portugol.analysis.*;

@SuppressWarnings("nls")
public final class AComSenaoSeDecl extends PSeDecl
{
    private TSe _se_;
    private TAbreParentese _abreParentese_;
    private PExpLogica _expLogica_;
    private TFechaParentese _fechaParentese_;
    private TEntao _entao_;
    private final LinkedList<PComandoSeq> _see_ = new LinkedList<PComandoSeq>();
    private PComando _cse_;
    private TPontoVirgula _pvse_;
    private TSenao _senao_;
    private final LinkedList<PComandoSeq> _senaoo_ = new LinkedList<PComandoSeq>();
    private PComando _csenao_;
    private TPontoVirgula _pvsenao_;
    private TFimSe _fimSe_;
    private TPontoVirgula _pvfim_;

    public AComSenaoSeDecl()
    {
        // Constructor
    }

    public AComSenaoSeDecl(
        @SuppressWarnings("hiding") TSe _se_,
        @SuppressWarnings("hiding") TAbreParentese _abreParentese_,
        @SuppressWarnings("hiding") PExpLogica _expLogica_,
        @SuppressWarnings("hiding") TFechaParentese _fechaParentese_,
        @SuppressWarnings("hiding") TEntao _entao_,
        @SuppressWarnings("hiding") List<?> _see_,
        @SuppressWarnings("hiding") PComando _cse_,
        @SuppressWarnings("hiding") TPontoVirgula _pvse_,
        @SuppressWarnings("hiding") TSenao _senao_,
        @SuppressWarnings("hiding") List<?> _senaoo_,
        @SuppressWarnings("hiding") PComando _csenao_,
        @SuppressWarnings("hiding") TPontoVirgula _pvsenao_,
        @SuppressWarnings("hiding") TFimSe _fimSe_,
        @SuppressWarnings("hiding") TPontoVirgula _pvfim_)
    {
        // Constructor
        setSe(_se_);

        setAbreParentese(_abreParentese_);

        setExpLogica(_expLogica_);

        setFechaParentese(_fechaParentese_);

        setEntao(_entao_);

        setSee(_see_);

        setCse(_cse_);

        setPvse(_pvse_);

        setSenao(_senao_);

        setSenaoo(_senaoo_);

        setCsenao(_csenao_);

        setPvsenao(_pvsenao_);

        setFimSe(_fimSe_);

        setPvfim(_pvfim_);

    }

    @Override
    public Object clone()
    {
        return new AComSenaoSeDecl(
            cloneNode(this._se_),
            cloneNode(this._abreParentese_),
            cloneNode(this._expLogica_),
            cloneNode(this._fechaParentese_),
            cloneNode(this._entao_),
            cloneList(this._see_),
            cloneNode(this._cse_),
            cloneNode(this._pvse_),
            cloneNode(this._senao_),
            cloneList(this._senaoo_),
            cloneNode(this._csenao_),
            cloneNode(this._pvsenao_),
            cloneNode(this._fimSe_),
            cloneNode(this._pvfim_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAComSenaoSeDecl(this);
    }

    public TSe getSe()
    {
        return this._se_;
    }

    public void setSe(TSe node)
    {
        if(this._se_ != null)
        {
            this._se_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._se_ = node;
    }

    public TAbreParentese getAbreParentese()
    {
        return this._abreParentese_;
    }

    public void setAbreParentese(TAbreParentese node)
    {
        if(this._abreParentese_ != null)
        {
            this._abreParentese_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._abreParentese_ = node;
    }

    public PExpLogica getExpLogica()
    {
        return this._expLogica_;
    }

    public void setExpLogica(PExpLogica node)
    {
        if(this._expLogica_ != null)
        {
            this._expLogica_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expLogica_ = node;
    }

    public TFechaParentese getFechaParentese()
    {
        return this._fechaParentese_;
    }

    public void setFechaParentese(TFechaParentese node)
    {
        if(this._fechaParentese_ != null)
        {
            this._fechaParentese_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fechaParentese_ = node;
    }

    public TEntao getEntao()
    {
        return this._entao_;
    }

    public void setEntao(TEntao node)
    {
        if(this._entao_ != null)
        {
            this._entao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._entao_ = node;
    }

    public LinkedList<PComandoSeq> getSee()
    {
        return this._see_;
    }

    public void setSee(List<?> list)
    {
        for(PComandoSeq e : this._see_)
        {
            e.parent(null);
        }
        this._see_.clear();

        for(Object obj_e : list)
        {
            PComandoSeq e = (PComandoSeq) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._see_.add(e);
        }
    }

    public PComando getCse()
    {
        return this._cse_;
    }

    public void setCse(PComando node)
    {
        if(this._cse_ != null)
        {
            this._cse_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cse_ = node;
    }

    public TPontoVirgula getPvse()
    {
        return this._pvse_;
    }

    public void setPvse(TPontoVirgula node)
    {
        if(this._pvse_ != null)
        {
            this._pvse_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pvse_ = node;
    }

    public TSenao getSenao()
    {
        return this._senao_;
    }

    public void setSenao(TSenao node)
    {
        if(this._senao_ != null)
        {
            this._senao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._senao_ = node;
    }

    public LinkedList<PComandoSeq> getSenaoo()
    {
        return this._senaoo_;
    }

    public void setSenaoo(List<?> list)
    {
        for(PComandoSeq e : this._senaoo_)
        {
            e.parent(null);
        }
        this._senaoo_.clear();

        for(Object obj_e : list)
        {
            PComandoSeq e = (PComandoSeq) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._senaoo_.add(e);
        }
    }

    public PComando getCsenao()
    {
        return this._csenao_;
    }

    public void setCsenao(PComando node)
    {
        if(this._csenao_ != null)
        {
            this._csenao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._csenao_ = node;
    }

    public TPontoVirgula getPvsenao()
    {
        return this._pvsenao_;
    }

    public void setPvsenao(TPontoVirgula node)
    {
        if(this._pvsenao_ != null)
        {
            this._pvsenao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pvsenao_ = node;
    }

    public TFimSe getFimSe()
    {
        return this._fimSe_;
    }

    public void setFimSe(TFimSe node)
    {
        if(this._fimSe_ != null)
        {
            this._fimSe_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fimSe_ = node;
    }

    public TPontoVirgula getPvfim()
    {
        return this._pvfim_;
    }

    public void setPvfim(TPontoVirgula node)
    {
        if(this._pvfim_ != null)
        {
            this._pvfim_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pvfim_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._se_)
            + toString(this._abreParentese_)
            + toString(this._expLogica_)
            + toString(this._fechaParentese_)
            + toString(this._entao_)
            + toString(this._see_)
            + toString(this._cse_)
            + toString(this._pvse_)
            + toString(this._senao_)
            + toString(this._senaoo_)
            + toString(this._csenao_)
            + toString(this._pvsenao_)
            + toString(this._fimSe_)
            + toString(this._pvfim_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._se_ == child)
        {
            this._se_ = null;
            return;
        }

        if(this._abreParentese_ == child)
        {
            this._abreParentese_ = null;
            return;
        }

        if(this._expLogica_ == child)
        {
            this._expLogica_ = null;
            return;
        }

        if(this._fechaParentese_ == child)
        {
            this._fechaParentese_ = null;
            return;
        }

        if(this._entao_ == child)
        {
            this._entao_ = null;
            return;
        }

        if(this._see_.remove(child))
        {
            return;
        }

        if(this._cse_ == child)
        {
            this._cse_ = null;
            return;
        }

        if(this._pvse_ == child)
        {
            this._pvse_ = null;
            return;
        }

        if(this._senao_ == child)
        {
            this._senao_ = null;
            return;
        }

        if(this._senaoo_.remove(child))
        {
            return;
        }

        if(this._csenao_ == child)
        {
            this._csenao_ = null;
            return;
        }

        if(this._pvsenao_ == child)
        {
            this._pvsenao_ = null;
            return;
        }

        if(this._fimSe_ == child)
        {
            this._fimSe_ = null;
            return;
        }

        if(this._pvfim_ == child)
        {
            this._pvfim_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._se_ == oldChild)
        {
            setSe((TSe) newChild);
            return;
        }

        if(this._abreParentese_ == oldChild)
        {
            setAbreParentese((TAbreParentese) newChild);
            return;
        }

        if(this._expLogica_ == oldChild)
        {
            setExpLogica((PExpLogica) newChild);
            return;
        }

        if(this._fechaParentese_ == oldChild)
        {
            setFechaParentese((TFechaParentese) newChild);
            return;
        }

        if(this._entao_ == oldChild)
        {
            setEntao((TEntao) newChild);
            return;
        }

        for(ListIterator<PComandoSeq> i = this._see_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PComandoSeq) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._cse_ == oldChild)
        {
            setCse((PComando) newChild);
            return;
        }

        if(this._pvse_ == oldChild)
        {
            setPvse((TPontoVirgula) newChild);
            return;
        }

        if(this._senao_ == oldChild)
        {
            setSenao((TSenao) newChild);
            return;
        }

        for(ListIterator<PComandoSeq> i = this._senaoo_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PComandoSeq) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._csenao_ == oldChild)
        {
            setCsenao((PComando) newChild);
            return;
        }

        if(this._pvsenao_ == oldChild)
        {
            setPvsenao((TPontoVirgula) newChild);
            return;
        }

        if(this._fimSe_ == oldChild)
        {
            setFimSe((TFimSe) newChild);
            return;
        }

        if(this._pvfim_ == oldChild)
        {
            setPvfim((TPontoVirgula) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
