/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.portugol.node;

import org.sablecc.portugol.analysis.*;

@SuppressWarnings("nls")
public final class AConjuncaoExpLogica3 extends PExpLogica3
{
    private PExpLogica3 _expLogica3_;
    private TConjuncao _conjuncao_;
    private PExpLogica4 _expLogica4_;

    public AConjuncaoExpLogica3()
    {
        // Constructor
    }

    public AConjuncaoExpLogica3(
        @SuppressWarnings("hiding") PExpLogica3 _expLogica3_,
        @SuppressWarnings("hiding") TConjuncao _conjuncao_,
        @SuppressWarnings("hiding") PExpLogica4 _expLogica4_)
    {
        // Constructor
        setExpLogica3(_expLogica3_);

        setConjuncao(_conjuncao_);

        setExpLogica4(_expLogica4_);

    }

    @Override
    public Object clone()
    {
        return new AConjuncaoExpLogica3(
            cloneNode(this._expLogica3_),
            cloneNode(this._conjuncao_),
            cloneNode(this._expLogica4_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAConjuncaoExpLogica3(this);
    }

    public PExpLogica3 getExpLogica3()
    {
        return this._expLogica3_;
    }

    public void setExpLogica3(PExpLogica3 node)
    {
        if(this._expLogica3_ != null)
        {
            this._expLogica3_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expLogica3_ = node;
    }

    public TConjuncao getConjuncao()
    {
        return this._conjuncao_;
    }

    public void setConjuncao(TConjuncao node)
    {
        if(this._conjuncao_ != null)
        {
            this._conjuncao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._conjuncao_ = node;
    }

    public PExpLogica4 getExpLogica4()
    {
        return this._expLogica4_;
    }

    public void setExpLogica4(PExpLogica4 node)
    {
        if(this._expLogica4_ != null)
        {
            this._expLogica4_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expLogica4_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expLogica3_)
            + toString(this._conjuncao_)
            + toString(this._expLogica4_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expLogica3_ == child)
        {
            this._expLogica3_ = null;
            return;
        }

        if(this._conjuncao_ == child)
        {
            this._conjuncao_ = null;
            return;
        }

        if(this._expLogica4_ == child)
        {
            this._expLogica4_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expLogica3_ == oldChild)
        {
            setExpLogica3((PExpLogica3) newChild);
            return;
        }

        if(this._conjuncao_ == oldChild)
        {
            setConjuncao((TConjuncao) newChild);
            return;
        }

        if(this._expLogica4_ == oldChild)
        {
            setExpLogica4((PExpLogica4) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
