/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.portugol.node;

import org.sablecc.portugol.analysis.*;

@SuppressWarnings("nls")
public final class ADisjuncaoExpLogica2 extends PExpLogica2
{
    private PExpLogica2 _expLogica2_;
    private TDisjuncao _disjuncao_;
    private PExpLogica3 _expLogica3_;

    public ADisjuncaoExpLogica2()
    {
        // Constructor
    }

    public ADisjuncaoExpLogica2(
        @SuppressWarnings("hiding") PExpLogica2 _expLogica2_,
        @SuppressWarnings("hiding") TDisjuncao _disjuncao_,
        @SuppressWarnings("hiding") PExpLogica3 _expLogica3_)
    {
        // Constructor
        setExpLogica2(_expLogica2_);

        setDisjuncao(_disjuncao_);

        setExpLogica3(_expLogica3_);

    }

    @Override
    public Object clone()
    {
        return new ADisjuncaoExpLogica2(
            cloneNode(this._expLogica2_),
            cloneNode(this._disjuncao_),
            cloneNode(this._expLogica3_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADisjuncaoExpLogica2(this);
    }

    public PExpLogica2 getExpLogica2()
    {
        return this._expLogica2_;
    }

    public void setExpLogica2(PExpLogica2 node)
    {
        if(this._expLogica2_ != null)
        {
            this._expLogica2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expLogica2_ = node;
    }

    public TDisjuncao getDisjuncao()
    {
        return this._disjuncao_;
    }

    public void setDisjuncao(TDisjuncao node)
    {
        if(this._disjuncao_ != null)
        {
            this._disjuncao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._disjuncao_ = node;
    }

    public PExpLogica3 getExpLogica3()
    {
        return this._expLogica3_;
    }

    public void setExpLogica3(PExpLogica3 node)
    {
        if(this._expLogica3_ != null)
        {
            this._expLogica3_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expLogica3_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expLogica2_)
            + toString(this._disjuncao_)
            + toString(this._expLogica3_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expLogica2_ == child)
        {
            this._expLogica2_ = null;
            return;
        }

        if(this._disjuncao_ == child)
        {
            this._disjuncao_ = null;
            return;
        }

        if(this._expLogica3_ == child)
        {
            this._expLogica3_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expLogica2_ == oldChild)
        {
            setExpLogica2((PExpLogica2) newChild);
            return;
        }

        if(this._disjuncao_ == oldChild)
        {
            setDisjuncao((TDisjuncao) newChild);
            return;
        }

        if(this._expLogica3_ == oldChild)
        {
            setExpLogica3((PExpLogica3) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
