/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.portugol.node;

import org.sablecc.portugol.analysis.*;

@SuppressWarnings("nls")
public final class ADisjuncaoxExpLogica2 extends PExpLogica2
{
    private PExpLogica2 _expLogica2_;
    private TDisjuncaoExc _disjuncaoExc_;
    private PExpLogica3 _expLogica3_;

    public ADisjuncaoxExpLogica2()
    {
        // Constructor
    }

    public ADisjuncaoxExpLogica2(
        @SuppressWarnings("hiding") PExpLogica2 _expLogica2_,
        @SuppressWarnings("hiding") TDisjuncaoExc _disjuncaoExc_,
        @SuppressWarnings("hiding") PExpLogica3 _expLogica3_)
    {
        // Constructor
        setExpLogica2(_expLogica2_);

        setDisjuncaoExc(_disjuncaoExc_);

        setExpLogica3(_expLogica3_);

    }

    @Override
    public Object clone()
    {
        return new ADisjuncaoxExpLogica2(
            cloneNode(this._expLogica2_),
            cloneNode(this._disjuncaoExc_),
            cloneNode(this._expLogica3_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADisjuncaoxExpLogica2(this);
    }

    public PExpLogica2 getExpLogica2()
    {
        return this._expLogica2_;
    }

    public void setExpLogica2(PExpLogica2 node)
    {
        if(this._expLogica2_ != null)
        {
            this._expLogica2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expLogica2_ = node;
    }

    public TDisjuncaoExc getDisjuncaoExc()
    {
        return this._disjuncaoExc_;
    }

    public void setDisjuncaoExc(TDisjuncaoExc node)
    {
        if(this._disjuncaoExc_ != null)
        {
            this._disjuncaoExc_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._disjuncaoExc_ = node;
    }

    public PExpLogica3 getExpLogica3()
    {
        return this._expLogica3_;
    }

    public void setExpLogica3(PExpLogica3 node)
    {
        if(this._expLogica3_ != null)
        {
            this._expLogica3_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expLogica3_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expLogica2_)
            + toString(this._disjuncaoExc_)
            + toString(this._expLogica3_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expLogica2_ == child)
        {
            this._expLogica2_ = null;
            return;
        }

        if(this._disjuncaoExc_ == child)
        {
            this._disjuncaoExc_ = null;
            return;
        }

        if(this._expLogica3_ == child)
        {
            this._expLogica3_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expLogica2_ == oldChild)
        {
            setExpLogica2((PExpLogica2) newChild);
            return;
        }

        if(this._disjuncaoExc_ == oldChild)
        {
            setDisjuncaoExc((TDisjuncaoExc) newChild);
            return;
        }

        if(this._expLogica3_ == oldChild)
        {
            setExpLogica3((PExpLogica3) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
