/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.portugol.node;

import org.sablecc.portugol.analysis.*;

@SuppressWarnings("nls")
public final class ANegadaExpLogica4 extends PExpLogica4
{
    private TNegacao _negacao_;
    private PExpLogica _expLogica_;

    public ANegadaExpLogica4()
    {
        // Constructor
    }

    public ANegadaExpLogica4(
        @SuppressWarnings("hiding") TNegacao _negacao_,
        @SuppressWarnings("hiding") PExpLogica _expLogica_)
    {
        // Constructor
        setNegacao(_negacao_);

        setExpLogica(_expLogica_);

    }

    @Override
    public Object clone()
    {
        return new ANegadaExpLogica4(
            cloneNode(this._negacao_),
            cloneNode(this._expLogica_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANegadaExpLogica4(this);
    }

    public TNegacao getNegacao()
    {
        return this._negacao_;
    }

    public void setNegacao(TNegacao node)
    {
        if(this._negacao_ != null)
        {
            this._negacao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._negacao_ = node;
    }

    public PExpLogica getExpLogica()
    {
        return this._expLogica_;
    }

    public void setExpLogica(PExpLogica node)
    {
        if(this._expLogica_ != null)
        {
            this._expLogica_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expLogica_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._negacao_)
            + toString(this._expLogica_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._negacao_ == child)
        {
            this._negacao_ = null;
            return;
        }

        if(this._expLogica_ == child)
        {
            this._expLogica_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._negacao_ == oldChild)
        {
            setNegacao((TNegacao) newChild);
            return;
        }

        if(this._expLogica_ == oldChild)
        {
            setExpLogica((PExpLogica) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
