/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.portugol.node;

import org.sablecc.portugol.analysis.*;

@SuppressWarnings("nls")
public final class ASeComando extends PComando
{
    private PSeDecl _seDecl_;

    public ASeComando()
    {
        // Constructor
    }

    public ASeComando(
        @SuppressWarnings("hiding") PSeDecl _seDecl_)
    {
        // Constructor
        setSeDecl(_seDecl_);

    }

    @Override
    public Object clone()
    {
        return new ASeComando(
            cloneNode(this._seDecl_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASeComando(this);
    }

    public PSeDecl getSeDecl()
    {
        return this._seDecl_;
    }

    public void setSeDecl(PSeDecl node)
    {
        if(this._seDecl_ != null)
        {
            this._seDecl_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._seDecl_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._seDecl_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._seDecl_ == child)
        {
            this._seDecl_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._seDecl_ == oldChild)
        {
            setSeDecl((PSeDecl) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
