/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.portugol.node;

import org.sablecc.portugol.analysis.*;

@SuppressWarnings("nls")
public final class ASequenciaVarVarSeq extends PVarSeq
{
    private PVar _var_;
    private TVirgula _virgula_;
    private PVarSeq _varSeq_;

    public ASequenciaVarVarSeq()
    {
        // Constructor
    }

    public ASequenciaVarVarSeq(
        @SuppressWarnings("hiding") PVar _var_,
        @SuppressWarnings("hiding") TVirgula _virgula_,
        @SuppressWarnings("hiding") PVarSeq _varSeq_)
    {
        // Constructor
        setVar(_var_);

        setVirgula(_virgula_);

        setVarSeq(_varSeq_);

    }

    @Override
    public Object clone()
    {
        return new ASequenciaVarVarSeq(
            cloneNode(this._var_),
            cloneNode(this._virgula_),
            cloneNode(this._varSeq_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASequenciaVarVarSeq(this);
    }

    public PVar getVar()
    {
        return this._var_;
    }

    public void setVar(PVar node)
    {
        if(this._var_ != null)
        {
            this._var_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._var_ = node;
    }

    public TVirgula getVirgula()
    {
        return this._virgula_;
    }

    public void setVirgula(TVirgula node)
    {
        if(this._virgula_ != null)
        {
            this._virgula_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._virgula_ = node;
    }

    public PVarSeq getVarSeq()
    {
        return this._varSeq_;
    }

    public void setVarSeq(PVarSeq node)
    {
        if(this._varSeq_ != null)
        {
            this._varSeq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._varSeq_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._var_)
            + toString(this._virgula_)
            + toString(this._varSeq_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._var_ == child)
        {
            this._var_ = null;
            return;
        }

        if(this._virgula_ == child)
        {
            this._virgula_ = null;
            return;
        }

        if(this._varSeq_ == child)
        {
            this._varSeq_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._var_ == oldChild)
        {
            setVar((PVar) newChild);
            return;
        }

        if(this._virgula_ == oldChild)
        {
            setVirgula((TVirgula) newChild);
            return;
        }

        if(this._varSeq_ == oldChild)
        {
            setVarSeq((PVarSeq) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
