/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.portugol.node;

import org.sablecc.portugol.analysis.*;

@SuppressWarnings("nls")
public final class ASimplesExpLogica3 extends PExpLogica3
{
    private PExpLogica4 _expLogica4_;

    public ASimplesExpLogica3()
    {
        // Constructor
    }

    public ASimplesExpLogica3(
        @SuppressWarnings("hiding") PExpLogica4 _expLogica4_)
    {
        // Constructor
        setExpLogica4(_expLogica4_);

    }

    @Override
    public Object clone()
    {
        return new ASimplesExpLogica3(
            cloneNode(this._expLogica4_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASimplesExpLogica3(this);
    }

    public PExpLogica4 getExpLogica4()
    {
        return this._expLogica4_;
    }

    public void setExpLogica4(PExpLogica4 node)
    {
        if(this._expLogica4_ != null)
        {
            this._expLogica4_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expLogica4_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expLogica4_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expLogica4_ == child)
        {
            this._expLogica4_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expLogica4_ == oldChild)
        {
            setExpLogica4((PExpLogica4) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
