/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.portugol.node;

import org.sablecc.portugol.analysis.*;

@SuppressWarnings("nls")
public final class ASomaOp extends POp
{
    private TSoma _soma_;

    public ASomaOp()
    {
        // Constructor
    }

    public ASomaOp(
        @SuppressWarnings("hiding") TSoma _soma_)
    {
        // Constructor
        setSoma(_soma_);

    }

    @Override
    public Object clone()
    {
        return new ASomaOp(
            cloneNode(this._soma_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASomaOp(this);
    }

    public TSoma getSoma()
    {
        return this._soma_;
    }

    public void setSoma(TSoma node)
    {
        if(this._soma_ != null)
        {
            this._soma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._soma_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._soma_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._soma_ == child)
        {
            this._soma_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._soma_ == oldChild)
        {
            setSoma((TSoma) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
