/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.portugol.node;

import org.sablecc.portugol.analysis.*;

@SuppressWarnings("nls")
public final class TComecaPrograma extends Token
{
    public TComecaPrograma()
    {
        super.setText("programa");
    }

    public TComecaPrograma(int line, int pos)
    {
        super.setText("programa");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TComecaPrograma(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTComecaPrograma(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TComecaPrograma text.");
    }
}
