/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.portugol.node;

import org.sablecc.portugol.analysis.*;

@SuppressWarnings("nls")
public final class TDisjuncaoExc extends Token
{
    public TDisjuncaoExc()
    {
        super.setText("xor");
    }

    public TDisjuncaoExc(int line, int pos)
    {
        super.setText("xor");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TDisjuncaoExc(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTDisjuncaoExc(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TDisjuncaoExc text.");
    }
}
