/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.portugol.node;

import org.sablecc.portugol.analysis.*;

@SuppressWarnings("nls")
public final class TLeiaConsole extends Token
{
    public TLeiaConsole()
    {
        super.setText("leia");
    }

    public TLeiaConsole(int line, int pos)
    {
        super.setText("leia");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TLeiaConsole(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTLeiaConsole(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TLeiaConsole text.");
    }
}
