/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.portugol.node;

import org.sablecc.portugol.analysis.*;

@SuppressWarnings("nls")
public final class TLogOu extends Token
{
    public TLogOu()
    {
        super.setText("ou");
    }

    public TLogOu(int line, int pos)
    {
        super.setText("ou");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TLogOu(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTLogOu(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TLogOu text.");
    }
}
